### ISSUE TITLE
JS error on Edit Submission page when clicking "Load History"

### ISSUE THREAD

**Issue by benkeen** [formtools/module-submission_history#10]
This was spotted by @willcwell, as described here: https://github.com/formtools/core/issues/556

Confirmed locally.

**Comment by benkeen** [comment]
Apologies @willcwell, this was caused accidentally when I refactored some of the Form Tools Core code and the hook reference got lost (i.e. the way this module ties in with the Core). I'll release 2.0.5 tonight which will contain a fix for this. Thanks!

**Comment by benkeen** [comment]
https://github.com/formtools/module-submission_history/releases/tag/2.0.5

**Comment by willcwell** [comment]
Ben – Whatever you did worked. Thank a million.
Please note the install is “folder name” specific.
Meaning I had to rename module-submission_history-2.0.5 to submission_history before I had an option to install it. Maybe I overlook this in the documentation.
module-submission_history-2.0.5  -------> submission_history
Thank again for all of your great work.
